### ISSUE TITLE
Complete Code in Example is not complete

### ISSUE THREAD

**Issue by tronta** [AaronErhardt/AaronErhardt.github.io#11]
In the complete example the `main` function is missing: https://aaronerhardt.github.io/relm4-book/book/reusable_components.html
It would be great if all examples could be executed by copy paste.

**Comment by AaronErhardt** [comment]
Well, in this case there's no main function. It's a component written for a library and the user needs to use this component in an actual application. See: https://aaronerhardt.github.io/relm4-book/book/reusable_components.html#conclusion

But maybe I should make this more clear?

**Comment by tronta** [comment]
People like me paste at the beginning the full code into the IDE and follow the code there. :smile: 
So I guess what would be cool, if there could be two files or a link to the repo

**Comment by AaronErhardt** [comment]
But there is a link to repo. The "alert" example is explicitly mentioned at the end. Or should I mention it at the top already?

**Comment by AaronErhardt** [comment]
Should be fixed now. I moved the comment to the top.
