### ISSUE TITLE
Explain postition function in FactoryPrototype trait

### ISSUE THREAD

**Issue by tronta** [AaronErhardt/AaronErhardt.github.io#24]
imho this chapter could be improved:
https://aaronerhardt.github.io/relm4-book/book/factory.html#the-position-function

When I read it, I still feel, like I don't have grasped what the index it.
Would it make sense to beef up the example a little bit?
What about having for the widget a box with a label (eg initial value) and then the button with the current value? Not sure if this helps, :smile: 
Or a link to a more complex example.

**Comment by AaronErhardt** [comment]
I hope the new text explains it better. I also added a small image: https://aaronerhardt.github.io/relm4-book/book/factory.html#the-position-function

**Comment by tronta** [comment]
Cool. I'm a big fan of visualization. However for it is a little bit confusing. For me it's not clear when which of the examples apply. Maybe it would help to add the used widget definition to the example.

**Comment by AaronErhardt** [comment]
I don't know what exactly you mean. You can use any layout you want if this is what you mean. The picture just shows two examples. But maybe I should add a link to the grid_factory example where the position property is actually used.

**Comment by tronta** [comment]
You need to know, that I have not much pre-knowledge (which is good for giving feedback) and I'm a simple person :smile:.
For me it this
> Because the factory can't guess where you want to add new widgets, you need to specify the widget placement in the position function. For example, you could have three elements per row or per column or any other layout you want.
with the pictures, does not explain enough how I can specify, the positions.

And here you write nothing about grid: https://aaronerhardt.github.io/docs/relm4/relm4/factory/collections/index.html 
Because I would assume that one would need also a two dimensional data type
Probably I'm just confused…

**Comment by AaronErhardt** [comment]
In this case you don't need a two dimensional data type. You just map the index to 2D grid space. See the grid_factory example that generates a chess grid pattern: https://github.com/AaronErhardt/relm4/blob/main/relm4-examples/examples/grid_factory.rs#L133

I think, I'll link the example in the book to show how the position function can be used. gtk::Grid is so far the only widget where this is really useful, anyway.

Is the chess grid too complex or can you understand how the widgets are placed in the example?

**Comment by tronta** [comment]
I would remove the grid example and point to a explanation somewhere else (as you proposed)

**Comment by AaronErhardt** [comment]
I've moved the explanation to a small extra chapter: https://aaronerhardt.github.io/relm4-book/book/factory.html#the-position-function

**Comment by tronta** [comment]
great
