### ISSUE TITLE
Give overview of available factories

### ISSUE THREAD

**Issue by tronta** [AaronErhardt/AaronErhardt.github.io#25]
in this chapter https://aaronerhardt.github.io/relm4-book/book/factory.html
I would find it valuable if you could give an overview of other exiting factories than FactoryVec and their properties (link to their documentation)

**Comment by AaronErhardt** [comment]
I've added this section to the docs: https://aaronerhardt.github.io/docs/relm4/relm4/factory/collections/index.html#which-factory-type-to-use

Where would you mention this in the book or is it enough to have it in the docs?

**Comment by tronta** [comment]
I'm a table person, but with only two it might be an overkill 😀
When I wrote this, I was not aware that there are just those two. The book keeps it somehow open, if those are sufficient or if others are planned. Maybe one sentence could help: currently there are two types available. Additional ones might come in future.
If you know what I mean... 
I'm just loud thinking. 
But if you want, you can also close it.

**Comment by tronta** [comment]
Maybe it is also worth mentioning, what happens if one uses a non Factory type, eg Vec and how it could be done best to modify/display data of eg a Vec?
Should one always use eg FactoryVec instead of Vec? How does it play together with other libraries like Serde.
Or should one copy/sync data between those structures? If yes, what is the best way.

**Comment by AaronErhardt** [comment]
You can use anything you want. Factories are just for convenience. Using a Vec has the problem that you need to generate you're UI somehow and a Vec doesn't provide any information for efficient UI updates by default. I should probably add methods to access or initialize the internal data (which is unsurprisingly stored in a Vec or VecDeque) so that you can use Serde with factories. 

Or did you have some specific problem or use-case in mind?

**Comment by tronta** [comment]
Yes, I guess I mean this. For learning relm, I'm trying to build a little program. In this program I want to edit/display data (in general) which is stored in a hierarchical Vec/little bit complexer data structure. And on different levels of the UI I want to display/edit a subset of it.
So in order to provide the data to the UI, I probably would need to provide it in an efficient way to be displayed.

Not sure if this would work, but would it be possible to split up data in two parts, one for storing/accessing the data in a standard way, and an other part for tracking changes (which could be also triggered manually), and then to handover it to the UI (loud thinking)?

**Comment by AaronErhardt** [comment]
Yes, of course. I think factories are probably only really useful for linear data (although in theory you could even have nested factories). If you need something more complex you will need to implement your own mechanism to track changes.

**Comment by AaronErhardt** [comment]
I've extended the docs: https://aaronerhardt.github.io/docs/relm4/relm4/factory/collections/index.html

I also mentioned the docs the first time the `FactoryVec` is introduced: https://aaronerhardt.github.io/relm4-book/book/factory.html#the-model
