### ISSUE TITLE
example with weak pointers

### ISSUE THREAD

**Issue by tronta** [AaronErhardt/AaronErhardt.github.io#27]
Imho it would be great to point here to an example with weak pointers: https://aaronerhardt.github.io/relm4-book/book/factory_advanced.html#the-message-type or give a hint how it's been done.
A short explanation (or link to documentation) what DynamicIndex is would be great.

**Comment by AaronErhardt** [comment]
It was actually quite simple to rewrite the factory_advanced example with weak pointers. I've opened up a new branch for it [here](https://github.com/AaronErhardt/relm4/blob/weak_factory_advanced/relm4-examples/examples/factory_advanced.rs). Do you think I should use weak pointers in the book or should I only link to the reworked factory_advanced example for people that are interested in an example that uses weak pointers?

**Comment by tronta** [comment]
That's great! Imho It would be definitely worth putting in the book (with some explanations)

**Comment by AaronErhardt** [comment]
The book now uses weak pointers, too. https://aaronerhardt.github.io/relm4-book/book/factory_advanced.html#the-message-type

If you think this is enough feel free to close this issue.
