### ISSUE TITLE
add screenshot of examples

### ISSUE THREAD

**Issue by tronta** [AaronErhardt/AaronErhardt.github.io#38]
[As people seem to like a visual imression of the programs to be built](https://www.reddit.com/r/rust/comments/pj7g8t/announcing_relm4_v01/hbwk80h?utm_source=share&utm_medium=web2x&context=3), what do you think about adding some to the book? (I can help)

- at the [firs page](https://aaronerhardt.github.io/relm4-book/book/)
- at the beginning of each page where an example is being created

**Comment by AaronErhardt** [comment]
I've added screenshots yesterday to the README and to the book at the end of every chapter where a code example was used. 

The question is whether it's better to have the images at the start or at the end...

**Comment by tronta** [comment]
You are great. 
I personally would say at the beginning as it seems to be a motivator for starting reading and not to be scared off by the wall of text.

**Comment by tronta** [comment]
It personally would think, that one variant of the design schema is enough.
What about asking this guy directly if he finds it better, or what he thinks about it?
Maybe private chat, or public in that threat.

**Comment by AaronErhardt** [comment]
You mean that I should use either light or dark theme?

I will probably come back to this later because I'm currently working on automating the build (and am quite busy anyway), see #40.

**Comment by tronta** [comment]
Yes, exactly. 
Don't worry, I can also prepare a PR for that, if I know your opinion.
