### ISSUE TITLE
Put rendered book in .gitgnore

### ISSUE THREAD

**Issue by Hofer-Julian** [AaronErhardt/AaronErhardt.github.io#40]
I'd suggest to put [the rendered book folder](https://github.com/AaronErhardt/AaronErhardt.github.io/tree/master/relm4-book/book) to `.gitignore`. Otherwise you'll just blow up your repo.

**Comment by AaronErhardt** [comment]
That's a great idea. But so far I was too lazy to setup a CI job that renders my hugo blog and the book and the docs of Relm4 so I just pushed the rendered versions to this repo. But if you already have an example for an GitHub pages workflow that'd be very helpful.

**Comment by Hofer-Julian** [comment]
We have this

https://github.com/gtk-rs/gtk4-rs/blob/master/.github/workflows/book.yml

**Comment by AaronErhardt** [comment]
Thanks, that really helped me a lot!

I've made some progress with the automated build. Now the book and the blog are available on the gh-pages branch. However the docs didn't work yet because they need libadwaita to be installed. Do you know whether there is a convenient solution to get libadwaita for the github workflow?

**Comment by Hofer-Julian** [comment]
You mean the c-library?

Mmmh, either you compile it yourself and cache it or maybe there are already pre-releases you can download on gitlab.gnome.org?

**Comment by AaronErhardt** [comment]
I guess the workflows are now all in place and working. I've already moved to the gh-pages branch and all my links are up as far I can tell.

Thanks, again for the suggestion and the helpful links! I think gitg will be delighted that it doesn't need to render such huge git diffs anymore :wink:

**Comment by Hofer-Julian** [comment]
Awesome! 😊
